name: Deploy to InfinityFree

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install LFTP
      run: sudo apt-get install lftp

    - name: Deploy files via FTP
      run: |
        lftp -e "
        open ftp://ftpupload.net;
        user if0_37099789 Adityabhise;
        mirror -R ./;
        bye;
        "
